apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    k8s.kuboard.cn/storageType: 第一个storageclass，以dev-01的/data/nfsdata目录为存储点
  name: dev-01
mountOptions: []
parameters:
  archiveOnDelete: 'false'
provisioner: nfs-dev-01
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

